apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  labels:
    app: identity-service
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: deepinnext/identity-service:latest
          ports:
            - containerPort: 80
          # volumeMounts:
          #   - name: config-volume
          #     mountPath: /app/config.yaml
          #     subPath: config.yaml
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1024Mi"
              cpu: "1"
    # volumes:
    #   - name: config-volume
    #     configMap:
    #       name: identity-service-config-file